apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deploy
  labels:
    app.kubernetes.io/name: weather-app
    description: web_app_weather_dell_deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: weather
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weather
    spec:
      containers:
      - name: weather-app-name
        image: 285484/weather-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: API_KEY_WEATHER
          value: "YXAFBQ9XYK8RHJQGXCVJWQ7M3"
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: weather-deploy-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weather-deploy
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
