apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deploy
  labels:
    app: "weather-app"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: "weather-app"
        image: 285484/weather-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: API_KEY_WEATHER
          valueFrom:
            secretKeyRef:
              name: weather-api
              key : "API_KEY_WEATHER"
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: weather-deploy-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weather-deploy
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80