apiVersion: v1
kind: Service
metadata:
  name: weather-service
  labels:
    app.kubernetes.io/name: weather-app
    description: web_app_weather_dell_services
spec:
  selector:
    app.kubernetes.io/name: weather
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80